### ISSUE TITLE
Error in loading weights

### ISSUE THREAD

**Issue by shubham-scisar** [sirbastiano/VDS2Raw#1]
I tried running the script using inference.py and giving image paths,also downloaded the weights and placed them in the **checkpoints directory**.But I am running into an issue which is as follows :
python inference.py --img_path D:\VDS2Raw-master\input_data --threshold 0.5 --device cpu
Loads checkpoint by local backend from path: checkpoint/epoch_239.pth
```
Traceback (most recent call last):
  File "inference.py", line 80, in <module>
    model = init_detector(config_file, checkpoint_file, device=args.device)
  File "d:\vds2raw-master\mmdetection\mmdet\apis\inference.py", line 73, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 346, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: checkpoint/epoch_239.pth can not be found.
```
It is unable to find epoch_239.pth file. Please guide.

**Comment by sirbastiano** [comment]
Thanks for reaching out. I will try to replicate your error and bug fix this. In the meanwhile, could you tell me on which OS are you running this ? Il giorno 19 mar 2024, alle ore 16:19, shubhamsharma1609 ***@***.***> ha scritto:﻿
I tried running the script using inference.py and giving image paths,also downloaded the weights and placed them in the checkpoints directory.But I am running into an issue which is as follows :
python inference.py --img_path D:\VDS2Raw-master\input_data --threshold 0.5 --device cpu
Loads checkpoint by local backend from path: checkpoint/epoch_239.pth
Traceback (most recent call last):
  File "inference.py", line 80, in <module>
    model = init_detector(config_file, checkpoint_file, device=args.device)
  File "d:\vds2raw-master\mmdetection\mmdet\apis\inference.py", line 73, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "C:\Users\shubh\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\checkpoint.py", line 346, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: checkpoint/epoch_239.pth can not be found.

It is unable to find epoch_239.pth file. Please guide.

**Comment by shubham-scisar** [comment]
@sirbastiano I am using Windows OS and used the conda environment to download and use all packages.I downloaded the weights and just renamed them as epoch_239.pth.Then it was working fine. Further I have some more questions which are not clear ,kindly clarify:

1) Should I use a particular tile size for inferencing ?
2) In case I have a level 2(L2A) tile id and I want to get the level 0 granules for it how can I fetch them ?

**Comment by sirbastiano** [comment]
The problem is caused by changing the download link of the weights file, referencing to another name.

Coming to your questions:

1. We recommend using the same tile size used during train & testing.
2. Level-0 data are not released to users at the moment.

**Comment by sirbastiano** [comment]
I changed the filename of the weight in the caller. 

Thanks for your feedback.
